# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1200, 800)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/res/icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1200, 120))
        self.label.setMinimumSize(QtCore.QSize(1200, 120))
        self.label.setText(_fromUtf8(""))
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8(":/res/res/daytime_editor_logo.png")))
        self.label.setObjectName(_fromUtf8("label"))
        self.settings_tree = QtGui.QTreeWidget(self.centralwidget)
        self.settings_tree.setGeometry(QtCore.QRect(20, 170, 341, 611))
        self.settings_tree.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.settings_tree.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.settings_tree.setProperty("showDropIndicator", False)
        self.settings_tree.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.settings_tree.setIndentation(25)
        self.settings_tree.setRootIsDecorated(True)
        self.settings_tree.setUniformRowHeights(False)
        self.settings_tree.setItemsExpandable(True)
        self.settings_tree.setAnimated(True)
        self.settings_tree.setAllColumnsShowFocus(False)
        self.settings_tree.setWordWrap(True)
        self.settings_tree.setObjectName(_fromUtf8("settings_tree"))
        item_0 = QtGui.QTreeWidgetItem(self.settings_tree)
        item_0.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled|QtCore.Qt.ItemIsTristate)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_0 = QtGui.QTreeWidgetItem(self.settings_tree)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        self.settings_tree.header().setCascadingSectionResizes(False)
        self.settings_tree.header().setDefaultSectionSize(200)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 130, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setKerning(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet(_fromUtf8("color: #eee;"))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(410, 250, 771, 551))
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Plain)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.lbl_current_setting = QtGui.QLabel(self.frame)
        self.lbl_current_setting.setGeometry(QtCore.QRect(0, 0, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setKerning(True)
        self.lbl_current_setting.setFont(font)
        self.lbl_current_setting.setStyleSheet(_fromUtf8("color: #222;"))
        self.lbl_current_setting.setObjectName(_fromUtf8("lbl_current_setting"))
        self.lbl_plugin_src = QtGui.QLabel(self.frame)
        self.lbl_plugin_src.setGeometry(QtCore.QRect(0, 30, 261, 16))
        self.lbl_plugin_src.setStyleSheet(_fromUtf8("color: #888;"))
        self.lbl_plugin_src.setObjectName(_fromUtf8("lbl_plugin_src"))
        self.pushButton = QtGui.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(670, 10, 101, 23))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.frame_3 = QtGui.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(0, 60, 771, 471))
        self.frame_3.setStyleSheet(_fromUtf8("QFrame {\n"
"background: #ddd;border: 1px solid #aaa;\n"
"}"))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.verticalLayoutWidget = QtGui.QWidget(self.frame_3)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 761, 461))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.prefab_edit_widget = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.prefab_edit_widget.setSpacing(0)
        self.prefab_edit_widget.setObjectName(_fromUtf8("prefab_edit_widget"))
        self.lbl_setting_desc = QtGui.QLabel(self.frame)
        self.lbl_setting_desc.setGeometry(QtCore.QRect(190, 30, 261, 16))
        self.lbl_setting_desc.setStyleSheet(_fromUtf8("color: #888;"))
        self.lbl_setting_desc.setObjectName(_fromUtf8("lbl_setting_desc"))
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, 120, 391, 681))
        self.frame_2.setStyleSheet(_fromUtf8("background: #1b1b1b;"))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.frame_4 = QtGui.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(410, 165, 771, 51))
        self.frame_4.setStyleSheet(_fromUtf8("QFrame {background: #ddd;border: 1px solid #aaa;}\n"
"QLabel {border: 0;}"))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.time_slider = QtGui.QSlider(self.frame_4)
        self.time_slider.setGeometry(QtCore.QRect(90, 12, 661, 31))
        self.time_slider.setMaximum(5184000)
        self.time_slider.setSingleStep(10000)
        self.time_slider.setPageStep(100000)
        self.time_slider.setProperty("value", 2592000)
        self.time_slider.setOrientation(QtCore.Qt.Horizontal)
        self.time_slider.setInvertedControls(False)
        self.time_slider.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.time_slider.setTickInterval(864000)
        self.time_slider.setObjectName(_fromUtf8("time_slider"))
        self.time_label = QtGui.QLabel(self.frame_4)
        self.time_label.setGeometry(QtCore.QRect(20, 11, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.time_label.setFont(font)
        self.time_label.setStyleSheet(_fromUtf8("color: #9a3;"))
        self.time_label.setObjectName(_fromUtf8("time_label"))
        self.lbl_time = QtGui.QLabel(self.centralwidget)
        self.lbl_time.setGeometry(QtCore.QRect(410, 130, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setKerning(True)
        self.lbl_time.setFont(font)
        self.lbl_time.setStyleSheet(_fromUtf8("color: #222;"))
        self.lbl_time.setObjectName(_fromUtf8("lbl_time"))
        self.frame_2.raise_()
        self.label.raise_()
        self.settings_tree.raise_()
        self.label_2.raise_()
        self.frame.raise_()
        self.frame_4.raise_()
        self.lbl_time.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Day Time Editor", None))
        self.settings_tree.headerItem().setText(0, _translate("MainWindow", "Setting", None))
        self.settings_tree.headerItem().setText(1, _translate("MainWindow", "Value", None))
        __sortingEnabled = self.settings_tree.isSortingEnabled()
        self.settings_tree.setSortingEnabled(False)
        self.settings_tree.topLevelItem(0).setText(0, _translate("MainWindow", "Ambient Occlusion", None))
        self.settings_tree.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "Occlusion Strength", None))
        self.settings_tree.topLevelItem(0).child(0).setText(1, _translate("MainWindow", "0.5", None))
        self.settings_tree.topLevelItem(1).setText(0, _translate("MainWindow", "Scattering", None))
        self.settings_tree.topLevelItem(1).child(0).setText(0, _translate("MainWindow", "Sun Height", None))
        self.settings_tree.topLevelItem(1).child(0).setText(1, _translate("MainWindow", "0,4", None))
        self.settings_tree.topLevelItem(1).child(1).setText(0, _translate("MainWindow", "Sun Angle", None))
        self.settings_tree.topLevelItem(1).child(1).setText(1, _translate("MainWindow", "180 °", None))
        self.settings_tree.topLevelItem(1).child(2).setText(0, _translate("MainWindow", "Sun Color", None))
        self.settings_tree.topLevelItem(1).child(2).setText(1, _translate("MainWindow", "[128, 255, 100]", None))
        self.settings_tree.setSortingEnabled(__sortingEnabled)
        self.label_2.setText(_translate("MainWindow", "Settings", None))
        self.lbl_current_setting.setText(_translate("MainWindow", "Occlusion Strength", None))
        self.lbl_plugin_src.setText(_translate("MainWindow", "Plugin: Ambient Occlusion", None))
        self.pushButton.setText(_translate("MainWindow", "Reset to Default", None))
        self.lbl_setting_desc.setText(_translate("MainWindow", "Description: Some Desc", None))
        self.time_label.setText(_translate("MainWindow", "11:15", None))
        self.lbl_time.setText(_translate("MainWindow", "Time", None))

import resources_rc
