/*
 * This file was generated by:
 * D:\P3D\1.9GIT\built_x64_buffered\bin\interrogate -fnames -string -refcount -assert -python-native -SD:\P3D\1.9GIT\built_x64_buffered\include/parser-inc -SD:\P3D\1.9GIT\built_x64_buffered\include/ -srcdir . -oc InterrogateWrapper.cpp -od Interrogate.in -module HSWKScattering -library HSWKScattering -nomangle -DINTERROGATE -DCPPPARSER -D__STDC__=1 -D__cplusplus=201103L -D__inline -D_X86_ -DWIN32_VC -DWIN32 -D_WIN32 -DWIN64_VC -DWIN64 -D_WIN64 -D_MSC_VER=1600 -D"__declspec(param)=" -D__cdecl -D_near -D_far -D__near -D__far -D__stdcall .\ArHosekSkyModel.h .\config_module.h .\HWSScattering.h 
 *
 */

#include "dtoolbase.h"
#include "interrogate_request.h"
#include "dconfig.h"
#include "pnotify.h"
#include <sstream>
#define PANDA_LIBRARY_NAME_HSWKScattering
#include "py_panda.h"
#include "extension.h"
#include "dcast.h"

#include "./ArHosekSkyModel.h"
#include "./HWSScattering.h"
#include "./config_module.h"
#include "ArHosekSkyModel.h"
#include "PNMImage.h"
#include "configVariableDouble.h"
#include "configVariableInt.h"
#include "configVariableString.h"
#include <iostream>
#include "notifyCategoryProxy.h"
#include "pandabase.h"
#include <stdlib.h>

#undef _POSIX_C_SOURCE
#undef _XOPEN_SOURCE
#define PY_SSIZE_T_CLEAN 1

#if PYTHON_FRAMEWORK
  #include <Python/Python.h>
#else
  #include "Python.h"
#endif

//********************************************************************
//*** prototypes for .. Global
//********************************************************************
//********************************************************************
//*** prototypes for .. External Objects
//********************************************************************

//********************************************************************
//*** Functions for .. Global
//********************************************************************
/******************************************************************
 * Python type method wrapper for
 * inline int generate_table(void)
 *******************************************************************/
static PyObject *Dtool_generate_table_1(PyObject *, PyObject *) {
  // 1-inline int generate_table(void)
  int return_value = generate_table();
  if (Dtool_CheckErrorOccurred()) {
    return NULL;
  }
  return PyLongOrInt_FromLong(return_value);
}

#ifndef NDEBUG
static const char *Dtool_generate_table_1_comment =
  "C++ Interface:\n"
  "generate_table()\n";
#else
static const char *Dtool_generate_table_1_comment = NULL;
#endif


//********************************************************************
//*** Module Object Linker ..
//********************************************************************
void Dtool_HSWKScattering_RegisterTypes() {
}

void Dtool_HSWKScattering_ResolveExternals() {
#ifndef LINK_ALL_STATIC
  // Resolve externally imported types.
#endif
}

void Dtool_HSWKScattering_BuildInstants(PyObject *module) {
  (void) module;
//********************************************************************
//*** Module Init Upcall ..  Externally Defined Class
//********************************************************************
}

static PyMethodDef python_simple_funcs[] = {
  {"generate_table", &Dtool_generate_table_1, METH_NOARGS, (const char *)Dtool_generate_table_1_comment},
  // Support Function For Dtool_types ... for now in each module ??
  {"Dtool_BorrowThisReference", &Dtool_BorrowThisReference, METH_VARARGS, "Used to borrow 'this' pointer (to, from)\nAssumes no ownership."},
  {"Dtool_AddToDictionary", &Dtool_AddToDictionary, METH_VARARGS, "Used to add items into a tp_dict"},
  {NULL, NULL, 0, NULL}
};

struct LibraryDef HSWKScattering_moddef = {python_simple_funcs};
static InterrogateModuleDef _in_module_def = {
  1452943618,  /* file_identifier */
  "HSWKScattering",  /* library_name */
  "be4N",  /* library_hash_name */
  "HSWKScattering",  /* module_name */
  "Interrogate.in",  /* database_filename */
  (InterrogateUniqueNameDef *)0,  /* unique_names */
  0,  /* num_unique_names */
  (void **)0,  /* fptrs */
  0,  /* num_fptrs */
  1,  /* first_index */
  4  /* next_index */
};

Configure(_in_configure_HSWKScattering);
ConfigureFn(_in_configure_HSWKScattering) {
  interrogate_request_module(&_in_module_def);
}

