# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Mon Aug 18 19:13:59 2014
#      by: PyQt4 UI code generator 4.11.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Voxel(object):
    def setupUi(self, Voxel):
        Voxel.setObjectName(_fromUtf8("Voxel"))
        Voxel.resize(505, 480)
        Voxel.setMinimumSize(QtCore.QSize(505, 480))
        Voxel.setMaximumSize(QtCore.QSize(505, 480))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/res/icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Voxel.setWindowIcon(icon)
        Voxel.setAutoFillBackground(True)
        self.centralwidget = QtGui.QWidget(Voxel)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 481, 121))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(139, 139, 139))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(209, 209, 209))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(174, 174, 174))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 69, 69))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(93, 93, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(139, 139, 139))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(197, 197, 197))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(139, 139, 139))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(209, 209, 209))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(174, 174, 174))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 69, 69))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(93, 93, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(139, 139, 139))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(197, 197, 197))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 69, 69))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(139, 139, 139))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(209, 209, 209))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(174, 174, 174))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 69, 69))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(93, 93, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 69, 69))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 69, 69))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(139, 139, 139))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(139, 139, 139))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(139, 139, 139))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.groupBox.setPalette(palette)
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.ipt_source = QtGui.QLineEdit(self.groupBox)
        self.ipt_source.setEnabled(True)
        self.ipt_source.setGeometry(QtCore.QRect(10, 50, 421, 21))
        self.ipt_source.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.ipt_source.setStyleSheet(_fromUtf8("background: #fff;"))
        self.ipt_source.setReadOnly(True)
        self.ipt_source.setObjectName(_fromUtf8("ipt_source"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 30, 181, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.btn_selectSource = QtGui.QPushButton(self.groupBox)
        self.btn_selectSource.setGeometry(QtCore.QRect(432, 49, 31, 23))
        self.btn_selectSource.setObjectName(_fromUtf8("btn_selectSource"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 451, 31))
        self.label_2.setStyleSheet(_fromUtf8("color: #888;"))
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 140, 481, 131))
        self.groupBox_2.setAutoFillBackground(False)
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(10, 20, 181, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.chb_gridSize16 = QtGui.QRadioButton(self.groupBox_2)
        self.chb_gridSize16.setGeometry(QtCore.QRect(10, 40, 41, 17))
        self.chb_gridSize16.setChecked(False)
        self.chb_gridSize16.setObjectName(_fromUtf8("chb_gridSize16"))
        self.chb_gridSize32 = QtGui.QRadioButton(self.groupBox_2)
        self.chb_gridSize32.setGeometry(QtCore.QRect(60, 40, 41, 17))
        self.chb_gridSize32.setObjectName(_fromUtf8("chb_gridSize32"))
        self.chb_gridSize64 = QtGui.QRadioButton(self.groupBox_2)
        self.chb_gridSize64.setGeometry(QtCore.QRect(110, 40, 41, 17))
        self.chb_gridSize64.setChecked(True)
        self.chb_gridSize64.setObjectName(_fromUtf8("chb_gridSize64"))
        self.chb_gridSize128 = QtGui.QRadioButton(self.groupBox_2)
        self.chb_gridSize128.setGeometry(QtCore.QRect(160, 40, 41, 17))
        self.chb_gridSize128.setObjectName(_fromUtf8("chb_gridSize128"))
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(10, 70, 181, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.box_borderSize = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.box_borderSize.setGeometry(QtCore.QRect(10, 90, 201, 22))
        self.box_borderSize.setDecimals(4)
        self.box_borderSize.setMinimum(0.01)
        self.box_borderSize.setMaximum(1000.0)
        self.box_borderSize.setSingleStep(0.1)
        self.box_borderSize.setProperty("value", 1.0)
        self.box_borderSize.setObjectName(_fromUtf8("box_borderSize"))
        self.chb_gridSize256 = QtGui.QRadioButton(self.groupBox_2)
        self.chb_gridSize256.setGeometry(QtCore.QRect(210, 40, 41, 17))
        self.chb_gridSize256.setObjectName(_fromUtf8("chb_gridSize256"))
        self.chb_gridSize512 = QtGui.QRadioButton(self.groupBox_2)
        self.chb_gridSize512.setGeometry(QtCore.QRect(260, 40, 41, 17))
        self.chb_gridSize512.setObjectName(_fromUtf8("chb_gridSize512"))
        self.btn_convert = QtGui.QPushButton(self.centralwidget)
        self.btn_convert.setGeometry(QtCore.QRect(320, 280, 81, 31))
        self.btn_convert.setObjectName(_fromUtf8("btn_convert"))
        self.processStatus = QtGui.QProgressBar(self.centralwidget)
        self.processStatus.setEnabled(False)
        self.processStatus.setGeometry(QtCore.QRect(10, 284, 311, 23))
        self.processStatus.setProperty("value", 0)
        self.processStatus.setObjectName(_fromUtf8("processStatus"))
        self.logOutput = QtGui.QPlainTextEdit(self.centralwidget)
        self.logOutput.setGeometry(QtCore.QRect(10, 320, 481, 151))
        self.logOutput.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.logOutput.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.logOutput.setReadOnly(True)
        self.logOutput.setObjectName(_fromUtf8("logOutput"))
        self.btn_showResult = QtGui.QPushButton(self.centralwidget)
        self.btn_showResult.setEnabled(False)
        self.btn_showResult.setGeometry(QtCore.QRect(410, 280, 81, 31))
        self.btn_showResult.setObjectName(_fromUtf8("btn_showResult"))
        Voxel.setCentralWidget(self.centralwidget)

        self.retranslateUi(Voxel)
        QtCore.QMetaObject.connectSlotsByName(Voxel)

    def retranslateUi(self, Voxel):
        Voxel.setWindowTitle(_translate("Voxel", "Voxelizer GUI", None))
        self.groupBox.setTitle(_translate("Voxel", "Source", None))
        self.ipt_source.setPlaceholderText(_translate("Voxel", "Select a .egg or .bam file to voxelize ..", None))
        self.label.setText(_translate("Voxel", "Source file (.egg or .bam)", None))
        self.btn_selectSource.setText(_translate("Voxel", "...", None))
        self.label_2.setText(_translate("Voxel", "Notice: The model may have missing textures. Textures are not required to generate the voxel grid. The grid will be stored relative to the model file in a folder called voxelized/.", None))
        self.groupBox_2.setTitle(_translate("Voxel", "Options", None))
        self.label_3.setText(_translate("Voxel", "Voxel Grid Size", None))
        self.chb_gridSize16.setText(_translate("Voxel", "16", None))
        self.chb_gridSize32.setText(_translate("Voxel", "32", None))
        self.chb_gridSize64.setText(_translate("Voxel", "64", None))
        self.chb_gridSize128.setText(_translate("Voxel", "128", None))
        self.label_6.setText(_translate("Voxel", "Border Size (Panda3D units)", None))
        self.chb_gridSize256.setText(_translate("Voxel", "256", None))
        self.chb_gridSize512.setText(_translate("Voxel", "512", None))
        self.btn_convert.setText(_translate("Voxel", "Convert", None))
        self.logOutput.setPlainText(_translate("Voxel", "Voxelizer GUI - Initialized ..", None))
        self.btn_showResult.setText(_translate("Voxel", "Show Result", None))

import resources_rc
