"""

Compares various results

"""

from __future__ import print_function

import os
import sys
import shutil

from panda3d.core import PNMImage

try:
    os.makedirs("batch_compare")
except:
    pass

overlay = PNMImage("res/overlay.png")

materials_to_test = []

materials_to_test.append({
        "name": "Test-R0",
        "diffuse": (0, 0, 0),
        "ior": 1.51,
        "roughness": 0.3
    })

materials_to_test.append({
        "name": "Test-IOR1.1",
        "diffuse": (0, 0, 1),
        "ior": 1.1,
        "roughness": 0.0
    })

materials_to_test.append({
        "name": "Test-IOR2",
        "diffuse": (0, 0, 1),
        "ior": 2.0,
        "roughness": 0.0
    })

materials_to_test.append({
        "name": "Test-IOR2.5",
        "diffuse": (0, 0, 1),
        "ior": 2.5,
        "roughness": 0.0
    })




for material in materials_to_test:

    print("Testing material", material["name"])

    # Write material def
    with open("_tmp_material.py", "w") as handle:
        handle.write("# Autogenerated\n")
        handle.write("name = '{}'".format(material["name"]) + "\n")
        handle.write("roughness = {}".format(material["roughness"]) + "\n")
        handle.write("ior = {}".format(material["ior"]) + "\n")
        handle.write("diffuse = {}".format(material["diffuse"]) + "\n")

    # run rp
    print("  Running RP ..")
    cmd = '"{}"'.format(sys.executable) + " -B run_renderpipeline.py > nul"
    os.system(cmd)

    print("  Running mitsuba ..")
    # run mitsuba
    with open("res/scene.templ.xml", "r") as handle:
        content = handle.read()

    content = content.replace("%ALPHA%", str(material["roughness"] * material["roughness"]))
    content = content.replace("%IOR%", str(material["ior"]))
    content = content.replace("%DIFFUSE%", str(material["diffuse"]).strip("()"))

    with open("res/scene.xml", "w") as handle:
        handle.write(content)

    os.system("run_mitsuba.bat > nul")

    print("  Writing result ..")
    img = PNMImage("scene-rp.png")
    img_ref = PNMImage("scene.png")

    img.copy_sub_image(img_ref, 256, 0, 256, 0, 256, 512)
    img.mult_sub_image(overlay, 0, 0)
    img.write("batch_compare/" + material["name"] + ".png")

try:
    os.remove("_tmp_material.py")
except:
    pass

print("Done!")
