# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1200, 800)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1200, 800))
        MainWindow.setMaximumSize(QtCore.QSize(1200, 800))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/Data/GUI/icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.lst_plugins = QtGui.QListWidget(self.centralwidget)
        self.lst_plugins.setGeometry(QtCore.QRect(20, 100, 251, 671))
        self.lst_plugins.setStyleSheet(_fromUtf8("QListWidget::item {\n"
"padding: 5px;\n"
"}"))
        self.lst_plugins.setObjectName(_fromUtf8("lst_plugins"))
        item = QtGui.QListWidgetItem()
        self.lst_plugins.addItem(item)
        item = QtGui.QListWidgetItem()
        self.lst_plugins.addItem(item)
        item = QtGui.QListWidgetItem()
        self.lst_plugins.addItem(item)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 30, 401, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.frame_details = QtGui.QFrame(self.centralwidget)
        self.frame_details.setGeometry(QtCore.QRect(300, 100, 881, 671))
        self.frame_details.setFrameShape(QtGui.QFrame.Box)
        self.frame_details.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_details.setLineWidth(1)
        self.frame_details.setObjectName(_fromUtf8("frame_details"))
        self.lbl_plugin_name = QtGui.QLabel(self.frame_details)
        self.lbl_plugin_name.setGeometry(QtCore.QRect(30, 20, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_plugin_name.setFont(font)
        self.lbl_plugin_name.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_plugin_name.setObjectName(_fromUtf8("lbl_plugin_name"))
        self.lbl_plugin_version = QtGui.QLabel(self.frame_details)
        self.lbl_plugin_version.setGeometry(QtCore.QRect(30, 50, 591, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lbl_plugin_version.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_plugin_version.setFont(font)
        self.lbl_plugin_version.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_plugin_version.setObjectName(_fromUtf8("lbl_plugin_version"))
        self.lbl_plugin_desc = QtGui.QLabel(self.frame_details)
        self.lbl_plugin_desc.setGeometry(QtCore.QRect(30, 70, 591, 91))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_plugin_desc.setFont(font)
        self.lbl_plugin_desc.setStyleSheet(_fromUtf8("color: #777"))
        self.lbl_plugin_desc.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_plugin_desc.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lbl_plugin_desc.setWordWrap(True)
        self.lbl_plugin_desc.setObjectName(_fromUtf8("lbl_plugin_desc"))
        self.table_plugin_settings = QtGui.QTableWidget(self.frame_details)
        self.table_plugin_settings.setGeometry(QtCore.QRect(30, 150, 831, 501))
        self.table_plugin_settings.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.table_plugin_settings.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.table_plugin_settings.setProperty("showDropIndicator", False)
        self.table_plugin_settings.setDragDropOverwriteMode(False)
        self.table_plugin_settings.setAlternatingRowColors(True)
        self.table_plugin_settings.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.table_plugin_settings.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.table_plugin_settings.setShowGrid(True)
        self.table_plugin_settings.setGridStyle(QtCore.Qt.SolidLine)
        self.table_plugin_settings.setWordWrap(True)
        self.table_plugin_settings.setCornerButtonEnabled(False)
        self.table_plugin_settings.setObjectName(_fromUtf8("table_plugin_settings"))
        self.table_plugin_settings.setColumnCount(4)
        self.table_plugin_settings.setRowCount(2)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.table_plugin_settings.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table_plugin_settings.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setBackground(QtGui.QColor(0, 150, 0))
        self.table_plugin_settings.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.table_plugin_settings.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table_plugin_settings.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.table_plugin_settings.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.table_plugin_settings.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.table_plugin_settings.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        self.table_plugin_settings.setItem(0, 3, item)
        item = QtGui.QTableWidgetItem()
        self.table_plugin_settings.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        self.table_plugin_settings.setItem(1, 2, item)
        item = QtGui.QTableWidgetItem()
        self.table_plugin_settings.setItem(1, 3, item)
        self.table_plugin_settings.horizontalHeader().setVisible(True)
        self.table_plugin_settings.horizontalHeader().setCascadingSectionResizes(True)
        self.table_plugin_settings.horizontalHeader().setHighlightSections(True)
        self.table_plugin_settings.horizontalHeader().setMinimumSectionSize(100)
        self.table_plugin_settings.horizontalHeader().setStretchLastSection(True)
        self.table_plugin_settings.verticalHeader().setVisible(False)
        self.table_plugin_settings.verticalHeader().setCascadingSectionResizes(False)
        self.table_plugin_settings.verticalHeader().setDefaultSectionSize(80)
        self.table_plugin_settings.verticalHeader().setHighlightSections(False)
        self.table_plugin_settings.verticalHeader().setMinimumSectionSize(100)
        self.table_plugin_settings.verticalHeader().setSortIndicatorShown(False)
        self.table_plugin_settings.verticalHeader().setStretchLastSection(False)
        self.lst_plugins.raise_()
        self.label.raise_()
        self.frame_details.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "RenderPipeline Plugin Configurator", None))
        __sortingEnabled = self.lst_plugins.isSortingEnabled()
        self.lst_plugins.setSortingEnabled(False)
        item = self.lst_plugins.item(0)
        item.setText(_translate("MainWindow", "Item 1", None))
        item = self.lst_plugins.item(1)
        item.setText(_translate("MainWindow", "Item 2", None))
        item = self.lst_plugins.item(2)
        item.setText(_translate("MainWindow", "Item 3", None))
        self.lst_plugins.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("MainWindow", "RenderPipeline Plugin Configurator", None))
        self.lbl_plugin_name.setText(_translate("MainWindow", "lbl_plugin_name", None))
        self.lbl_plugin_version.setText(_translate("MainWindow", "lbl_plugin_version", None))
        self.lbl_plugin_desc.setText(_translate("MainWindow", "lbl_plugin_desc\n"
"Plugin Desc Line 2\n"
"Plugin Desc Line 3\n"
"Plugin Desc Line 4\n"
"", None))
        item = self.table_plugin_settings.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Row", None))
        item = self.table_plugin_settings.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Row2", None))
        item = self.table_plugin_settings.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name", None))
        item = self.table_plugin_settings.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Default", None))
        item = self.table_plugin_settings.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Current Value", None))
        item = self.table_plugin_settings.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Description", None))
        __sortingEnabled = self.table_plugin_settings.isSortingEnabled()
        self.table_plugin_settings.setSortingEnabled(False)
        item = self.table_plugin_settings.item(0, 1)
        item.setText(_translate("MainWindow", "DefaultRow0", None))
        item = self.table_plugin_settings.item(0, 2)
        item.setText(_translate("MainWindow", "CurrentRow0", None))
        item = self.table_plugin_settings.item(0, 3)
        item.setText(_translate("MainWindow", "DescRow0", None))
        item = self.table_plugin_settings.item(1, 1)
        item.setText(_translate("MainWindow", "DefaultRow1", None))
        item = self.table_plugin_settings.item(1, 2)
        item.setText(_translate("MainWindow", "CurrentRow1", None))
        item = self.table_plugin_settings.item(1, 3)
        item.setText(_translate("MainWindow", "DescRow1", None))
        self.table_plugin_settings.setSortingEnabled(__sortingEnabled)

import resources_rc
