
pipelineDir = "../../"


sourceDirectories = ["Code/", "Toolkit/", "Shader/", "Config/"]
ignorePattern = ["Code/AutoGenerated/", "Shader/FXAA",
                 "Shader/Includes/SMAA.include", "qt/main.py", "qt/resources_rc.py", "__init__.py"]

print "Code Analyzer v0.1"

from os import listdir
from os.path import join, isfile


def convertPath(pth):
    return pth.replace("\\", "/").rstrip("/")


def countLines(filename):
    with open(filename, "r") as handle:
        content = handle.readlines()
    return len(content)

currentIndent = 0

def analyzeDirectory(src):
    global currentIndent

    currentIndent += 1
    # prefix = "  " * currentIndent
    # print prefix,"Analyzing", src

    lines = 0
    for f in listdir(src):
        abspath = join(src, f)
        ignoreFile = False
        for ignore in ignorePattern:
            if convertPath(ignore) in convertPath(abspath):
                ignoreFile = True
                break

        if ignoreFile:
            continue

        if isfile(abspath):
            if (
                    f.endswith(".py") or
                    f.endswith(".compute") or
                    f.endswith(".fragment") or
                    f.endswith(".vertex") or
                    f.endswith(".ini") or
                    f.endswith(".include") or
                    f.endswith(".geometry") or
                    f.endswith(".glsl")):
                lines += countLines(abspath)
        else:
            lines += analyzeDirectory(abspath)

    currentIndent -= 1

    return lines

totalLines = 0

for src in sourceDirectories:
    lines = analyzeDirectory(join(pipelineDir, src))
    totalLines += lines
    print "  -> Directory", src, "has", lines, "Code Lines"

print "Total Lines of Code: ", totalLines
