# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1000, 680)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 680))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 680))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/res/icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet(_fromUtf8(""))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.lst_plugins = QtGui.QListWidget(self.centralwidget)
        self.lst_plugins.setGeometry(QtCore.QRect(20, 110, 251, 481))
        self.lst_plugins.setStyleSheet(_fromUtf8("QListWidget::item {\n"
"padding: 7px 3px;\n"
"background: #555;\n"
"outline: 0 !important;\n"
"margin-bottom: 3px;\n"
"margin-right: 10px;\n"
"color: #eee;\n"
"}\n"
"\n"
"QListWidget::item:hover {\n"
"background: #5c5c5c;\n"
"}\n"
"\n"
"QListWidget::item:selected {\n"
"background: #4f8027;\n"
"}\n"
"\n"
"QListWidget {\n"
"padding: 0;\n"
"color: #eee;\n"
"background: #cdcdcd;\n"
"/*\n"
"background: #222;\n"
"padding: 5px 8px;\n"
"border: 1px solid #444;\n"
"*/\n"
"}\n"
"\n"
"* {\n"
"outline: 0;\n"
"}\n"
""))
        self.lst_plugins.setFrameShape(QtGui.QFrame.NoFrame)
        self.lst_plugins.setLineWidth(0)
        self.lst_plugins.setObjectName(_fromUtf8("lst_plugins"))
        item = QtGui.QListWidgetItem()
        self.lst_plugins.addItem(item)
        item = QtGui.QListWidgetItem()
        self.lst_plugins.addItem(item)
        item = QtGui.QListWidgetItem()
        self.lst_plugins.addItem(item)
        item = QtGui.QListWidgetItem()
        self.lst_plugins.addItem(item)
        item = QtGui.QListWidgetItem()
        self.lst_plugins.addItem(item)
        item = QtGui.QListWidgetItem()
        self.lst_plugins.addItem(item)
        item = QtGui.QListWidgetItem()
        self.lst_plugins.addItem(item)
        item = QtGui.QListWidgetItem()
        self.lst_plugins.addItem(item)
        item = QtGui.QListWidgetItem()
        self.lst_plugins.addItem(item)
        item = QtGui.QListWidgetItem()
        self.lst_plugins.addItem(item)
        item = QtGui.QListWidgetItem()
        self.lst_plugins.addItem(item)
        item = QtGui.QListWidgetItem()
        self.lst_plugins.addItem(item)
        item = QtGui.QListWidgetItem()
        self.lst_plugins.addItem(item)
        item = QtGui.QListWidgetItem()
        self.lst_plugins.addItem(item)
        item = QtGui.QListWidgetItem()
        self.lst_plugins.addItem(item)
        self.frame_details = QtGui.QFrame(self.centralwidget)
        self.frame_details.setGeometry(QtCore.QRect(290, 65, 711, 611))
        self.frame_details.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_details.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_details.setLineWidth(1)
        self.frame_details.setObjectName(_fromUtf8("frame_details"))
        self.lbl_plugin_name = QtGui.QLabel(self.frame_details)
        self.lbl_plugin_name.setGeometry(QtCore.QRect(30, 20, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_plugin_name.setFont(font)
        self.lbl_plugin_name.setStyleSheet(_fromUtf8("color: #222;"))
        self.lbl_plugin_name.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_plugin_name.setObjectName(_fromUtf8("lbl_plugin_name"))
        self.lbl_plugin_version = QtGui.QLabel(self.frame_details)
        self.lbl_plugin_version.setGeometry(QtCore.QRect(30, 50, 481, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(79, 128, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(79, 128, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(79, 128, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(79, 128, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(79, 128, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(79, 128, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(79, 128, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(79, 128, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(79, 128, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.lbl_plugin_version.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_plugin_version.setFont(font)
        self.lbl_plugin_version.setStyleSheet(_fromUtf8("color: #4f8027;"))
        self.lbl_plugin_version.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_plugin_version.setObjectName(_fromUtf8("lbl_plugin_version"))
        self.lbl_plugin_desc = QtGui.QLabel(self.frame_details)
        self.lbl_plugin_desc.setGeometry(QtCore.QRect(30, 70, 591, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_plugin_desc.setFont(font)
        self.lbl_plugin_desc.setStyleSheet(_fromUtf8("color: #777"))
        self.lbl_plugin_desc.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_plugin_desc.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lbl_plugin_desc.setWordWrap(True)
        self.lbl_plugin_desc.setObjectName(_fromUtf8("lbl_plugin_desc"))
        self.table_plugin_settings = QtGui.QTableWidget(self.frame_details)
        self.table_plugin_settings.setGeometry(QtCore.QRect(30, 130, 671, 471))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.table_plugin_settings.setFont(font)
        self.table_plugin_settings.setFrameShape(QtGui.QFrame.StyledPanel)
        self.table_plugin_settings.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.table_plugin_settings.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.table_plugin_settings.setProperty("showDropIndicator", False)
        self.table_plugin_settings.setDragDropOverwriteMode(False)
        self.table_plugin_settings.setAlternatingRowColors(True)
        self.table_plugin_settings.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.table_plugin_settings.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.table_plugin_settings.setTextElideMode(QtCore.Qt.ElideNone)
        self.table_plugin_settings.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.table_plugin_settings.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.table_plugin_settings.setShowGrid(True)
        self.table_plugin_settings.setGridStyle(QtCore.Qt.SolidLine)
        self.table_plugin_settings.setWordWrap(True)
        self.table_plugin_settings.setCornerButtonEnabled(False)
        self.table_plugin_settings.setObjectName(_fromUtf8("table_plugin_settings"))
        self.table_plugin_settings.setColumnCount(4)
        self.table_plugin_settings.setRowCount(2)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.table_plugin_settings.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table_plugin_settings.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table_plugin_settings.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.table_plugin_settings.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table_plugin_settings.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.table_plugin_settings.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.table_plugin_settings.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.table_plugin_settings.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        self.table_plugin_settings.setItem(0, 3, item)
        item = QtGui.QTableWidgetItem()
        self.table_plugin_settings.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        self.table_plugin_settings.setItem(1, 2, item)
        item = QtGui.QTableWidgetItem()
        self.table_plugin_settings.setItem(1, 3, item)
        self.table_plugin_settings.horizontalHeader().setVisible(True)
        self.table_plugin_settings.horizontalHeader().setCascadingSectionResizes(True)
        self.table_plugin_settings.horizontalHeader().setHighlightSections(True)
        self.table_plugin_settings.horizontalHeader().setMinimumSectionSize(100)
        self.table_plugin_settings.horizontalHeader().setStretchLastSection(True)
        self.table_plugin_settings.verticalHeader().setVisible(False)
        self.table_plugin_settings.verticalHeader().setCascadingSectionResizes(False)
        self.table_plugin_settings.verticalHeader().setDefaultSectionSize(80)
        self.table_plugin_settings.verticalHeader().setHighlightSections(False)
        self.table_plugin_settings.verticalHeader().setMinimumSectionSize(100)
        self.table_plugin_settings.verticalHeader().setSortIndicatorShown(False)
        self.table_plugin_settings.verticalHeader().setStretchLastSection(False)
        self.btn_reset_plugin_settings = QtGui.QPushButton(self.frame_details)
        self.btn_reset_plugin_settings.setGeometry(QtCore.QRect(540, 20, 161, 31))
        self.btn_reset_plugin_settings.setObjectName(_fromUtf8("btn_reset_plugin_settings"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1000, 65))
        self.label.setStyleSheet(_fromUtf8("border: 3px solid #000;\n"
"border-width: 0 0 0px 0;"))
        self.label.setText(_fromUtf8(""))
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8(":/res/res/plugin_configurator_logo.png")))
        self.label.setObjectName(_fromUtf8("label"))
        self.lbl_select_plugin = QtGui.QLabel(self.centralwidget)
        self.lbl_select_plugin.setGeometry(QtCore.QRect(460, 330, 391, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_select_plugin.setFont(font)
        self.lbl_select_plugin.setStyleSheet(_fromUtf8("color: #888;"))
        self.lbl_select_plugin.setObjectName(_fromUtf8("lbl_select_plugin"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 60, 291, 621))
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet(_fromUtf8("background: #cdcdcd; border-right: 1px solid #aaa;"))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.lbl_plugin_name_2 = QtGui.QLabel(self.frame)
        self.lbl_plugin_name_2.setGeometry(QtCore.QRect(20, 20, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setKerning(False)
        self.lbl_plugin_name_2.setFont(font)
        self.lbl_plugin_name_2.setStyleSheet(_fromUtf8("color: #444;border: 0;"))
        self.lbl_plugin_name_2.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_plugin_name_2.setObjectName(_fromUtf8("lbl_plugin_name_2"))
        self.lbl_hint_restart = QtGui.QLabel(self.frame)
        self.lbl_hint_restart.setGeometry(QtCore.QRect(20, 550, 241, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(107, 107, 107))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(205, 205, 205))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(205, 205, 205))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(205, 205, 205))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(107, 107, 107))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(205, 205, 205))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(205, 205, 205))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(205, 205, 205))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(205, 205, 205))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(205, 205, 205))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(205, 205, 205))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.lbl_hint_restart.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.lbl_hint_restart.setFont(font)
        self.lbl_hint_restart.setStyleSheet(_fromUtf8("border-top: 1px solid #aaa;\n"
"border-right: 0px solid #9A3;"))
        self.lbl_hint_restart.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_hint_restart.setScaledContents(False)
        self.lbl_hint_restart.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_hint_restart.setWordWrap(True)
        self.lbl_hint_restart.setObjectName(_fromUtf8("lbl_hint_restart"))
        self.lbl_restart_pipeline = QtGui.QLabel(self.centralwidget)
        self.lbl_restart_pipeline.setGeometry(QtCore.QRect(500, 18, 391, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_restart_pipeline.setFont(font)
        self.lbl_restart_pipeline.setAutoFillBackground(False)
        self.lbl_restart_pipeline.setStyleSheet(_fromUtf8("color: #F44;background: #eee;padding: 5px; border-radius: 2px;"))
        self.lbl_restart_pipeline.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_restart_pipeline.setObjectName(_fromUtf8("lbl_restart_pipeline"))
        self.frame.raise_()
        self.lst_plugins.raise_()
        self.frame_details.raise_()
        self.label.raise_()
        self.lbl_select_plugin.raise_()
        self.lbl_restart_pipeline.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Plugin Configurator", None))
        __sortingEnabled = self.lst_plugins.isSortingEnabled()
        self.lst_plugins.setSortingEnabled(False)
        item = self.lst_plugins.item(0)
        item.setText(_translate("MainWindow", "  Item 1", None))
        item = self.lst_plugins.item(1)
        item.setText(_translate("MainWindow", "  Item", None))
        item = self.lst_plugins.item(2)
        item.setText(_translate("MainWindow", "  Item", None))
        item = self.lst_plugins.item(3)
        item.setText(_translate("MainWindow", "  Item", None))
        item = self.lst_plugins.item(4)
        item.setText(_translate("MainWindow", "  Item", None))
        item = self.lst_plugins.item(5)
        item.setText(_translate("MainWindow", "  Item", None))
        item = self.lst_plugins.item(6)
        item.setText(_translate("MainWindow", "  Item", None))
        item = self.lst_plugins.item(7)
        item.setText(_translate("MainWindow", "  Item", None))
        item = self.lst_plugins.item(8)
        item.setText(_translate("MainWindow", "  Item", None))
        item = self.lst_plugins.item(9)
        item.setText(_translate("MainWindow", "  Item", None))
        item = self.lst_plugins.item(10)
        item.setText(_translate("MainWindow", "  Item", None))
        item = self.lst_plugins.item(11)
        item.setText(_translate("MainWindow", "  Item", None))
        item = self.lst_plugins.item(12)
        item.setText(_translate("MainWindow", "  Item", None))
        item = self.lst_plugins.item(13)
        item.setText(_translate("MainWindow", "  Item 2", None))
        item = self.lst_plugins.item(14)
        item.setText(_translate("MainWindow", "  Item 3", None))
        self.lst_plugins.setSortingEnabled(__sortingEnabled)
        self.lbl_plugin_name.setText(_translate("MainWindow", "lbl_plugin_name", None))
        self.lbl_plugin_version.setText(_translate("MainWindow", "lbl_plugin_version", None))
        self.lbl_plugin_desc.setText(_translate("MainWindow", "lbl_plugin_desc\n"
"Plugin Desc Line 2\n"
"Plugin Desc Line 3", None))
        item = self.table_plugin_settings.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Row", None))
        item = self.table_plugin_settings.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Row2", None))
        item = self.table_plugin_settings.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Setting", None))
        item = self.table_plugin_settings.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Default", None))
        item = self.table_plugin_settings.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Current Value", None))
        item = self.table_plugin_settings.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Description", None))
        __sortingEnabled = self.table_plugin_settings.isSortingEnabled()
        self.table_plugin_settings.setSortingEnabled(False)
        item = self.table_plugin_settings.item(0, 1)
        item.setText(_translate("MainWindow", "DefaultRow0", None))
        item = self.table_plugin_settings.item(0, 2)
        item.setText(_translate("MainWindow", "CurrentRow0", None))
        item = self.table_plugin_settings.item(0, 3)
        item.setText(_translate("MainWindow", "DescRow0", None))
        item = self.table_plugin_settings.item(1, 1)
        item.setText(_translate("MainWindow", "DefaultRow1", None))
        item = self.table_plugin_settings.item(1, 2)
        item.setText(_translate("MainWindow", "CurrentRow1", None))
        item = self.table_plugin_settings.item(1, 3)
        item.setText(_translate("MainWindow", "DescRow1", None))
        self.table_plugin_settings.setSortingEnabled(__sortingEnabled)
        self.btn_reset_plugin_settings.setText(_translate("MainWindow", "Reset Settings of this Plugin", None))
        self.lbl_select_plugin.setText(_translate("MainWindow", "Select a plugin on the left side to change its settings", None))
        self.lbl_plugin_name_2.setText(_translate("MainWindow", "Installed Plugins", None))
        self.lbl_hint_restart.setText(_translate("MainWindow", "Settings with a green background are changeable while the pipeline is running, all other settings require a pipeline restart.", None))
        self.lbl_restart_pipeline.setText(_translate("MainWindow", "Pipeline needs to be restarted in order to see all changes!", None))

from . import resources_rc
